spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: user
    password: 
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 9909