DROP TABLE IF EXISTS TBL_TESTJPA;
  
CREATE TABLE EXPLORE (
  ids INT AUTO_INCREMENT  PRIMARY KEY,
  names VARCHAR(250) NOT NULL,
  flags BOOLEAN(250) DEFAULT NULL,
  times TIME NOT NULL,
  dates DATE NOT NULL,
  timestamps TIMESTAMP NOT NULL
);